spring:
  application:
    name: brokerage-firm
  datasource:
    url: jdbc:h2:mem:brokeragedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG